# to list all models
# curl "https://generativelanguage.googleapis.com/v1beta/models?key=$GEMINI_API_KEY"|jq

model_list:
  - model_name: gemini-3-flash
    litellm_params:
      model: gemini/gemini-3.1-flash-lite-preview
      api_key: "os.environ/GEMINI_API_KEY"
      
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-3.1-pro-preview
      api_key: "os.environ/GEMINI_API_KEY"
  
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: "os.environ/GEMINI_API_KEY"

litellm_settings:
  drop_params: true

