block drop from any to 93.123.73.115
block drop from any to "haritonov.kulichki.net"
block drop from any to "webtoon.xyz"
block drop from any to "loveread.ec"
block drop from any to "redtube.com"
block drop from any to "lurkmore.to"
block drop from any to "fmovies.wtf"
block drop from any to "readmanhwa.com"
block drop from any to "webtoon.xyz"
block drop from any to "haritonov.wiki"
block drop from any to "allking.club"
block drop from any to "www.xvideos.com"
block drop from any to "www.pornhub.com"
block drop from any to "www.xvideos.com"
block drop from any to "jp.xhamster.com"
#youtube.com
#sudo pfctl -e -f /etc/pf.conf
