#!/bin/sh

pip3 install $*
python=${SYSTEM_PYTHON-python} # https://www.cyberciti.biz/faq/bash-ksh-if-variable-is-not-defined-set-default-variable/
$python /Users/nailbiter/for/forpython/fordatawise/non-reusable/pre-install.py install $*
