.PHONY: test

#global consts
GCC_KEYS=-std=c99
#procedures
test: 505
	prove

#main
505: 505_main.c 505_Binary_Search_Tree_2.h 505_Binary_Search_Tree_2.c
	gcc 505_main.c 505_Binary_Search_Tree_2.c $(GCC_KEYS) -o $@
