version: '3.1'

services:

  app:
    ports:
      - 5000:5000
    build: .    

  mongo:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      
